image: node

cache:
  paths:
    - node_modules
    - .next/cache

prettier:
  script:
    - yarn
    - yarn check-prettier

pages:
  stage: deploy
  script:
    - yarn build
    - rm -rf public
    - mv out public
  artifacts:
    paths:
      - public
